# will be storing all the configurations

params:
  epochs: 30
  batch_size: 32
  num_classes: 10
  input_shape: [28,28]
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  validation_data_size: 5000
  patience: 5
  optimizer: SGD

artifects:
  artifects_dir: artifects
  model_dir: model
  plots_dir: plots
  checkpoint_dir: checkpoints
  model_name: model.h5

logs:
  log_dir: logs_dir
  general_logs: general_logs
  tensorboard_logs: tensorflow_logs

